[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Christian Hagau", email = "hagau@ibr.cs.tu-bs.de"},
]
dependencies = [
    "matplotlib",
    "numpy",
    "jsonpickle",
    "ujson",
    "pandas",
    "scipy>=1.8.1",
    "SQLAlchemy",
    "seaborn",
    "sphinx",
    "numpydoc",
    "sphinx-rtd-theme",
    "recommonmark",
    "jupyterlab",
    "ipympl",
    "tabulate",
    "bottleneck",
    "numexpr",
    "pyarrow",
    "tables",
    "dask>=2022.10.2",
    "dask-jobqueue",
    "dask-labextension",
    "semgrep",
    "matplotlib",
    "numpy",
    "jsonpickle",
    "ujson",
    "pandas",
    "SQLAlchemy",
    "seaborn",
    "sphinx",
    "numpydoc",
    "sphinx-rtd-theme",
    "recommonmark",
    "jupyterlab",
    "ipympl",
    "tabulate",
    "bottleneck",
    "numexpr",
    "pyarrow",
    "tables",
    "dask[complete]",
    "dask-jobqueue",
    "dask-labextension",
    "semgrep",
    "distributed>=2022.10.2",
    "graphviz>=0.20.1",
    "ipycytoscape>=1.3.3",
]
requires-python = ">=3.8,<3.11"
license = {text = "GPL3"}
[project.optional-dependencies]

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool]
[tool.pdm]
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[tool.pdm.dev-dependencies]
dev = [
    "pylint>=2.15.5",
    "autopep8",
    "wrapt",
    "typed-ast",
    "rope",
    "pycodestyle",
    "mccabe",
    "lazy-object-proxy",
    "isort",
    "astroid",
    "mypy>=0.982",
    "autoflake>=1.7.7",
]
